#Enable Automatic Updater?
Updater:
  #Check for updates? (Set to false to totaly disable the Updater (And /uc update))
  check: true
  #Download the updates automaticly? (When disabled you can still use /uc update to download)
  download: false
#Enable Pugin Metrics (MCstats.org)
Metrics: true
#Allow this plugin to connect to the mojang servers?
Mojang: true
#Language of the plugin (See Messages folder)
#You can add a custom one by creating a new file and put the name of the file here.
Language: EN

Afk:
  #Is the afk system enabled?
  Enabled: true
  #How long does it take before someone is marked as afk? (In seconds)
  AfkTime: 180
  #Kick players when they are afk for too long? (In seconds)
  KickEnabled: true
  #How long does it take before someone is kicked for being inactive? (In seconds) (Including the time before the player was marked as afk)
  KickTime: 900

#Enable instant respawning?
InstantRespawn: false

Blood:
  #Enable blood?
  Enabled: false
  #Enable it for players only?
  PlayersOnly: false

#Dynmap support (Nothing happens without Dynmap)
Dynmap:
  Enable: true
  #Show warps?
  Warps: true
  #Warps that are not shown, you can even use world:someworld to show no warps in that world.
  Hiddenwarps:
  - hiddenwarp1
  - hiddenwarp2
  - hiddenwarp3

Economy:
  #How is the money amount displayed?
  #Use %Amount for the value
  format: "$%Amount"
  #What is the currency name? (Used for Vault compatibility)
  currencyName: "dollar"
  #What is the currency name in plural? (Also used for Vault compatibility)
  currencyNamePlural: "dollars"
Explode:
  #Disable explosions? (True = disabled)
  Creeper: false
  TNT: false
  Ghast: false
  Enderdragon: false
  Wither: false
  Lightning: false

Messages:
  #Are the messages shown in the chat?
  Enabledchat: false
  #Are the messages shown in the bossbar?
  Enabledbossbar: false
  #Are the messages shown in the action bar?
  Enabledactionbar: false
  #Show the messages in a random order?
  Randomise: false
  #The time until the next message is shown (In seconds)
  Time: 120
  #(Only for the bossbar) Let the bossbar decrease until the next message?
  Decrease: true
  #Use messages.txt to change the messages.

Autosave:
  #Enable autosaving?
  Enabled: true
  #Show a message each autosave?
  Message: false
  #The time between each autosave. (In seconds)
  Time: 300

Timber:
  #Enable timber?
  Enable: false
  #Destroy leaves too? (Drops loot)
  Leaves: true
  #Take all durability of the logs from the axe?
  AllDurability: true
  #Do you need to have an axe in your hand to use Timber?
  NeedAxe: true

Weather:
  #Disable rain and thunder? (True = Disabled)
  Rain: false

#Chat customization
Chat:
  #How is the /alert command displayed?
  AlertFormat: "&0[&4&lALERT&0] @2%Message"
  #How is the /broadcast command displayed?
  BroadcastFormat: "&6[&e&lBROADCAST&6] @2%Message"
  #How is the /me command displayed?
  MeFormat: "&7* %Player %Message"
  #How is the /msg command displayed?
  MsgFormat: "@1[@2%Player1 @1-> @2%Player2@1] &e%Message"
  #How is the /msg command displayed for spies?
  MsgFormatSpy: "&7[&f%Player1 &7-> &f%Player2&7] &f%Message"
  #How is the /say command displayed?
  SayFormat: "&5[&d%Player&5] %Message"
  #How is the /ask command displayed?
  AskFormat: "@1%Player asked: &e%Message"
  #How is the /answer command displayed?
  AnswerFormat: "@1%Player answered: &e%Message"

  #The UltimateCore message colors
  #A link of all chatcolors, enter them without the '&':
  #http://ess.khhq.net/mc/
  #[@1] The default UltimateCore message color (Default = Dark aqua)
  Default: 3
  #[@2] The message color for values, like player names (Default = aqua)
  Value: b
  #[@3] The message color when there is a problem, like too less arguments (Default = red)
  Error: c

  #Enable the custom chat of UltimateCore? If false Filters are still enabled!
  EnableCustomChat: true

  #What is the format?
  #+Group = Group name (If vault installed, else empty)
  #+Prefix = Group prefix (If vault installed, else empty)
  #+Suffix = Group suffix (If vault installed, else empty)
  #+Name = Raw name
  #+Displayname = Displayname [WARNING: Some plugins automaticly set the rank/faction/etc before the players displayname]
  #+World = Current World name
  #+WorldAlias = First letter of the worlds name
  #+Message = Message the player is trying to send
  #+Town = The town the player is in (Towny)
  #+Faction = The faction the player is in (Factions)
  #Color codes supported!
  Format: '&6+Prefix&6+Displayname: &r+Suffix+Message'

  #Group formats: [REQUIRES VAULT + PERMISSION PLUGIN]
  #Every group that is not registered here uses the Global format
  Groups:
    Enabled: false
    #+Group = Group name (If vault installed, else empty)
    #+Prefix = Group prefix (If vault installed, else empty)
    #+Suffix = Group suffix (If vault installed, else empty)
    #+Name = Raw name
    #+Displayname = Displayname [WARNING: Some plugins automaticly set the rank/faction/etc before the players displayname]
    #+World = Current World name
    #+WorldAlias = First letter of the worlds name
    #+Message = Message the player is trying to send
    #+Town = The town the player is in (Towny)
    #+Faction = The faction the player is in (Factions)
    #Color codes supported!
    #GROUP NAMES ARE CASE SENSITIVE!!!
    Player: '&9[&6Player&9] &6+Displayname: &f+Message'
    Admin: '&6[&4Admin&6] &6+Displayname: &f+Message'
  Tab:
    #Are tab prefixes enabled?
    Enabled: false
    #The default tab prefix
    TabDefault: '&e'
    #Groups tab prefixes
    #Watchout! Too long prefixes can short player names for some characters
    #GROUP NAMES ARE CASE SENSITIVE!!!
    Player: '&6'
    Admin: '&4'
  #Enable spam/swear/etc filter?
  SpamFilter: true
  SwearFilter: false
  RepeatFilter: true
  CapsFilter: true
  UrlFilter: true
  IpFilter: true

#Command customization
Command:
  #Enable the custom unknown command message?
  UnknownCommand: true
  #Broadcast when someone gets banned?
  BanBroadcast: true
  #Remove positive effects when being healed?
  HealPositive: false
  #Home limits for permissions. Default limit is 1
  HomeLimits:
    #Player with uc.sethome.member has 2 homes
    member: 2
    #Player with uc.sethome.vip has 5 homes
    vip: 5
    #Player with uc.sethome.unlimited has infinite homes
  Jail:
    #Allow jailed players to move?
    move: true
    #Allow jailed players to talk?
    talk: true
    #Teleport players to the spawn when unjailed?
    spawn: true
  Save:
    #Show autosave messages?
    autosaveMessage: false
  Smite:
    #Is smite just an effect, or is it real? (False = Effect)
    smiteDamage: false
  Teleport:
    #The delay until the teleport ask request is cancelled in seconds
    TpaCancel: 30
    #Enable delay?
    EnableDelay: false
    #The delay. (In seconds)
    Delay: 5
  Spawn:
    # Set this to 'lowest', if you want the world (or multiverse) to handle the respawning.
    # Set this to 'high', if you want UltimateCore to handle the respawning.
    # Set this to 'highest', if you want to force UltimateCore to handle the respawning.
    Priority: high
